### ISSUE TITLE
Function 'os_log' does not exist in module 'os'

### ISSUE THREAD

**Issue by stormychel** [illescasDaniel/SwiftJson#1]
I get this error: Function 'os_log' does not exist in module 'os' after adding the package to my project.

This is in Logger.swift.

Any idea on how to solve / avoid?

![Screenshot 2021-04-19 at 11 54 46](https://user-images.githubusercontent.com/3184001/115217692-0cb50e00-a106-11eb-86cd-c5198c29df4b.png)

**Comment by illescasDaniel** [comment]
That's true, thank you, I probably mistyped that AFTER I compiled the module so I didn't notice.

This is now fixed in version 1.0.1, the tests run fine too. Try this version and if it works fine for your, close this issue please.

Thanks!

**Comment by stormychel** [comment]
> That's true, thank you, I probably mistyped that AFTER I compiled the module so I didn't notice.
> 
> This is now fixed in version 1.0.1, the tests run fine too. Try this version and if it works fine for your close this issue please.
> 
> Thanks!

Yes, 1.0.1 does the trick, thanks for your quick response!
